# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spare
email: hello@sparerides.com
description: >
  Spare matches riders with passengers going similar directions
  in Vancouver.  Earn money as a driver and get where you need to go as a rider!
  Available on the UBC-Broadway Corridor.
baseurl: ""
url: "https://sparerides.com" # the base hostname & protocol for your site
twitter_username: sparerides

# Build settings
markdown: kramdown
